question_data = {
    "response_code": 0,
    "results": [
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "Hippopotomonstrosesquippedaliophobia is the irrational fear of long words.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                           "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                                           "incorrect_answers": ["False"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Skateboarding will be included in the 2020 Summer Olympics in Tokyo.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                           "question": "MacOS is based on Linux.", "correct_answer": "False",
                                           "incorrect_answers": ["True"]},
        {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
         "question": "The television show Doctor Who first aired in 1963.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Animals", "type": "boolean", "difficulty": "medium", "question": "The Platypus is a mammal.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The French word for &quot;glass&quot; is &quot;glace&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                          "question": "Japan has left-hand side traffic.", "correct_answer": "True",
                                          "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In Monster Hunter Generations, guild style is a type of hunting style.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]}]}
